import { WeeklyMetric, Campaign, Lead, AccountMetric } from './types';

// Data for historical trends
export const trendData = [
  {
    week: 'Week 1',
    cr: 31.53,
    rr: 25.45,
    scheduled: 0,
    conducted: 1,
    sent: 295,
    accepted: 93,
    messages: 110
  },
  {
    week: 'Week 2',
    cr: 30.70,
    rr: 22.35,
    scheduled: 5,
    conducted: 1,
    sent: 430,
    accepted: 132,
    messages: 170
  },
  {
    week: 'Week 3',
    cr: 26.75,
    rr: 23.00,
    scheduled: 7,
    conducted: 7,
    sent: 557,
    accepted: 149,
    messages: 231
  },
  {
    week: 'Week 4',
    cr: 27.36,
    rr: 19.00,
    scheduled: 10,
    conducted: 7,
    sent: 497,
    accepted: 136,
    messages: 175
  },
  {
    week: 'Week 5',
    cr: 31.84,
    rr: 25.00,
    scheduled: 11,
    conducted: 7,
    sent: 716,
    accepted: 228,
    messages: 339
  },
  {
    week: 'Week 6',
    cr: 28.89,
    rr: 21.00,
    scheduled: 25,
    conducted: 4,
    sent: 1066,
    accepted: 308,
    messages: 460
  },
  {
    week: 'Week 7',
    cr: 36.58,
    rr: 23.00,
    scheduled: 15,
    conducted: 10,
    sent: 842,
    accepted: 308,
    messages: 534
  },
];

export const weeklyData: WeeklyMetric[] = [
  { week: 'Week 1', period: '29-4 jan 2026', sent: 295, accepted: 93, cr: 31.53, messages: 110, replies: 28, rr: 25.45, scheduled: 0, conducted: 1, comment: 'была назначена на прошлой неделе' },
  { week: 'Week 2', period: '5-11 jan 2026', sent: 430, accepted: 132, cr: 30.70, messages: 170, replies: 38, rr: 22.35, scheduled: 5, conducted: 1 },
  { week: 'Week 3', period: '12-18 jan 2026', sent: 557, accepted: 149, cr: 26.75, messages: 231, replies: 53, rr: 23.00, scheduled: 7, conducted: 7 },
  { week: 'Week 4', period: '19-25 jan 2026', sent: 497, accepted: 136, cr: 27.36, messages: 175, replies: 33, rr: 19.00, scheduled: 10, conducted: 7 },
  { week: 'Week 5', period: '26 Jan - 1 Feb 2026', sent: 716, accepted: 228, cr: 31.84, messages: 339, replies: 84, rr: 25.00, scheduled: 11, conducted: 7 },
  { week: 'Week 6', period: '2-8 Feb 2026', sent: 1066, accepted: 308, cr: 28.89, messages: 460, replies: 98, rr: 21.00, scheduled: 25, conducted: 4 },
  { week: 'Week 7', period: '9-15 feb 2026', sent: 842, accepted: 308, cr: 36.58, messages: 534, replies: 124, rr: 23.00, scheduled: 25, conducted: 10 },
];

export const allCampaigns: Record<string, Campaign[]> = {
  'Week 1': [
    { id: 'w1-1', name: '21 nov / exBlackTower', status: 'Top Performer', sent: 5, accepted: 3, cr: '60.0%', messages: 3, replies: 1, rr: '33.3%', scheduled: 0 },
    { id: 'w1-2', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Top Performer', sent: 15, accepted: 11, cr: '73.3%', messages: 16, replies: 4, rr: '25.0%', scheduled: 0 },
    { id: 'w1-3', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 20, accepted: 6, cr: '30.0%', messages: 9, replies: 3, rr: '33.3%', scheduled: 0 },
    { id: 'w1-4', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 25, accepted: 10, cr: '40.0%', messages: 10, replies: 2, rr: '20.0%', scheduled: 0 },
    { id: 'w1-5', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 30, accepted: 6, cr: '20.0%', messages: 8, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w1-6', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Top Performer', sent: 29, accepted: 15, cr: '51.7%', messages: 19, replies: 7, rr: '36.8%', scheduled: 0 },
    { id: 'w1-7', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 28, accepted: 12, cr: '42.9%', messages: 15, replies: 2, rr: '13.3%', scheduled: 0 },
    { id: 'w1-8', name: "UAE - Angel investors - 2.10 (Dima's base)", status: 'Scale', sent: 16, accepted: 4, cr: '25.0%', messages: 9, replies: 1, rr: '11.1%', scheduled: 0 },
    { id: 'w1-9', name: 'exDeVereGroup - 19.08', status: 'Scale', sent: 12, accepted: 3, cr: '25.0%', messages: 2, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w1-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Attention', sent: 47, accepted: 1, cr: '2.1%', messages: 1, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w1-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Scale', sent: 35, accepted: 11, cr: '31.4%', messages: 14, replies: 3, rr: '21.4%', scheduled: 0 },
    { id: 'w1-12', name: '13.12 /South Africa / private investors', status: 'Scale', sent: 33, accepted: 6, cr: '18.2%', messages: 4, replies: 2, rr: '50.0%', scheduled: 0 },
  ],
  'Week 2': [
    { id: 'w2-1', name: '21 nov / exBlackTower', status: 'Scale', sent: 22, accepted: 4, cr: '18.2%', messages: 4, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w2-2', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Scale', sent: 40, accepted: 17, cr: '42.5%', messages: 17, replies: 2, rr: '11.8%', scheduled: 1 },
    { id: 'w2-3', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 15, accepted: 6, cr: '40.0%', messages: 10, replies: 2, rr: '20.0%', scheduled: 0 },
    { id: 'w2-4', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 28, accepted: 7, cr: '25.0%', messages: 15, replies: 4, rr: '26.7%', scheduled: 1 },
    { id: 'w2-5', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 48, accepted: 13, cr: '27.1%', messages: 12, replies: 1, rr: '8.3%', scheduled: 0 },
    { id: 'w2-6', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Top Performer', sent: 47, accepted: 20, cr: '42.6%', messages: 23, replies: 2, rr: '8.7%', scheduled: 0 },
    { id: 'w2-7', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 39, accepted: 12, cr: '30.8%', messages: 18, replies: 5, rr: '27.8%', scheduled: 1 },
    { id: 'w2-8', name: "UAE - Angel investors - 2.10 (Dima's base)", status: 'Top Performer', sent: 29, accepted: 17, cr: '58.6%', messages: 13, replies: 2, rr: '15.4%', scheduled: 1 },
    { id: 'w2-9', name: 'exDeVereGroup - 19.08', status: 'Top Performer', sent: 25, accepted: 13, cr: '52.0%', messages: 8, replies: 1, rr: '12.5%', scheduled: 0 },
    { id: 'w2-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Attention', sent: 66, accepted: 2, cr: '3.0%', messages: 3, replies: 1, rr: '33.3%', scheduled: 0 },
    { id: 'w2-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Scale', sent: 37, accepted: 14, cr: '37.8%', messages: 23, replies: 4, rr: '17.4%', scheduled: 1 },
    { id: 'w2-12', name: '13.12 /South Africa / private investors', status: 'Scale', sent: 34, accepted: 2, cr: '5.9%', messages: 6, replies: 4, rr: '66.7%', scheduled: 0 },
  ],
  'Week 3': [
    { id: 'w3-1', name: '21 nov / exBlackTower', status: 'Top Performer', sent: 3, accepted: 3, cr: '100.0%', messages: 3, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w3-2', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Scale', sent: 63, accepted: 18, cr: '28.6%', messages: 26, replies: 10, rr: '38.5%', scheduled: 1 },
    { id: 'w3-3', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 7, accepted: 2, cr: '28.6%', messages: 6, replies: 1, rr: '16.7%', scheduled: 1 },
    { id: 'w3-4', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 29, accepted: 5, cr: '17.2%', messages: 10, replies: 1, rr: '10.0%', scheduled: 1 },
    { id: 'w3-5', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 137, accepted: 14, cr: '10.2%', messages: 17, replies: 3, rr: '17.6%', scheduled: 0 },
    { id: 'w3-6', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 55, accepted: 27, cr: '49.1%', messages: 30, replies: 4, rr: '13.3%', scheduled: 0 },
    { id: 'w3-7', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 48, accepted: 14, cr: '29.2%', messages: 22, replies: 4, rr: '18.2%', scheduled: 2 },
    { id: 'w3-8', name: "UAE - Angel investors - 2.10 (Dima's base)", status: 'Scale', sent: 52, accepted: 16, cr: '30.8%', messages: 19, replies: 3, rr: '15.8%', scheduled: 0 },
    { id: 'w3-9', name: 'exDeVereGroup - 19.08', status: 'Scale', sent: 34, accepted: 13, cr: '38.2%', messages: 15, replies: 1, rr: '6.7%', scheduled: 0 },
    { id: 'w3-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Scale', sent: 86, accepted: 6, cr: '7.0%', messages: 4, replies: 2, rr: '50.0%', scheduled: 0 },
    { id: 'w3-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Top Performer', sent: 25, accepted: 15, cr: '60.0%', messages: 27, replies: 8, rr: '29.6%', scheduled: 1 },
    { id: 'w3-12', name: '13.12 /South Africa / private investors', status: 'Top Performer', sent: 18, accepted: 11, cr: '61.1%', messages: 12, replies: 6, rr: '50.0%', scheduled: 1 },
  ],
  'Week 4': [
    { id: 'w4-1', name: '21 nov / exBlackTower', status: 'Scale', sent: 3, accepted: 0, cr: '0,0%', messages: 0, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-2', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Scale', sent: 47, accepted: 17, cr: '36,2%', messages: 19, replies: 6, rr: '31,6%', scheduled: 2 },
    { id: 'w4-3', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Top Performer', sent: 2, accepted: 1, cr: '50,0%', messages: 1, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-4', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 12, accepted: 4, cr: '33,3%', messages: 8, replies: 2, rr: '25,0%', scheduled: 0 },
    { id: 'w4-5', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 213, accepted: 39, cr: '18,3%', messages: 29, replies: 2, rr: '6,9%', scheduled: 2 },
    { id: 'w4-6', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 45, accepted: 17, cr: '37,8%', messages: 27, replies: 4, rr: '14,8%', scheduled: 1 },
    { id: 'w4-7', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 46, accepted: 15, cr: '32,6%', messages: 16, replies: 2, rr: '12,5%', scheduled: 0 },
    { id: 'w4-8', name: "UAE - Angel investors - 2.10 (Dima's base)", status: 'Scale', sent: 39, accepted: 10, cr: '25,6%', messages: 12, replies: 2, rr: '16,7%', scheduled: 0 },
    { id: 'w4-9', name: 'exDeVereGroup - 19.08', status: 'Scale', sent: 26, accepted: 8, cr: '30,8%', messages: 8, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Scale', sent: 18, accepted: 3, cr: '16,7%', messages: 5, replies: 1, rr: '20,0%', scheduled: 1 },
    { id: 'w4-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Top Performer', sent: 17, accepted: 8, cr: '47,1%', messages: 13, replies: 3, rr: '23,1%', scheduled: 1 },
    { id: 'w4-12', name: '13.12 /South Africa / private investors', status: 'Top Performer', sent: 5, accepted: 4, cr: '80,0%', messages: 4, replies: 2, rr: '50,0%', scheduled: 2 },
    { id: 'w4-13', name: '22.01 / investors CIS / face-to-face meeting', status: 'Scale', sent: 8, accepted: 0, cr: '0,0%', messages: 0, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-14', name: '22.01 / investors Georgia / face-to-face meeting', status: 'Scale', sent: 0, accepted: 0, cr: '0,0%', messages: 0, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-15', name: '22.01 / financial advisors Georgia / face-to-face meeting', status: 'Scale', sent: 7, accepted: 0, cr: '0,0%', messages: 0, replies: 0, rr: '0,0%', scheduled: 0 },
    { id: 'w4-16', name: '22.01 / financial advisors CIS / face-to-face meeting', status: 'Scale', sent: 7, accepted: 1, cr: '14,3%', messages: 0, replies: 0, rr: '0,0%', scheduled: 0 },
  ],
  'Week 5': [
    { id: 'w5-1', name: '21 nov / exBlackTower', status: 'Kill', sent: 2, accepted: 0, cr: '0.0%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w5-2', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Scale', sent: 59, accepted: 18, cr: '30.5%', messages: 34, replies: 9, rr: '26.5%', scheduled: 4 },
    { id: 'w5-3', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Kill', sent: 0, accepted: 0, cr: '#DIV/0!', messages: 1, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w5-4', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 25, accepted: 10, cr: '40.0%', messages: 14, replies: 3, rr: '21.4%', scheduled: 0 },
    { id: 'w5-5', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 57, accepted: 9, cr: '15.8%', messages: 58, replies: 12, rr: '20.7%', scheduled: 2 },
    { id: 'w5-6', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Top Performer', sent: 47, accepted: 24, cr: '51.1%', messages: 54, replies: 7, rr: '13.0%', scheduled: 0 },
    { id: 'w5-7', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 47, accepted: 8, cr: '17.0%', messages: 28, replies: 5, rr: '17.9%', scheduled: 0 },
    { id: 'w5-8', name: "UAE - Angel investors - 2.10 (Dima's base)", status: 'Scale', sent: 33, accepted: 9, cr: '27.3%', messages: 31, replies: 9, rr: '29.0%', scheduled: 2 },
    { id: 'w5-9', name: 'exDeVereGroup - 19.08', status: 'Scale', sent: 16, accepted: 2, cr: '12.5%', messages: 10, replies: 2, rr: '20.0%', scheduled: 0 },
    { id: 'w5-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Attention', sent: 57, accepted: 2, cr: '3.5%', messages: 6, replies: 3, rr: '50.0%', scheduled: 0 },
    { id: 'w5-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Top Performer', sent: 13, accepted: 6, cr: '46.2%', messages: 14, replies: 6, rr: '42.9%', scheduled: 1 },
    { id: 'w5-12', name: '13.12 /South Africa / private investors', status: 'Scale', sent: 2, accepted: 0, cr: '0.0%', messages: 4, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w5-13', name: '22.01 / investors CIS / face-to-face meeting', status: 'Scale', sent: 92, accepted: 19, cr: '20.7%', messages: 8, replies: 3, rr: '37.5%', scheduled: 1 },
    { id: 'w5-14', name: '22.01 / investors Georgia / face-to-face meeting', status: 'Scale', sent: 92, accepted: 30, cr: '32.6%', messages: 24, replies: 8, rr: '33.3%', scheduled: 1 },
    { id: 'w5-15', name: '22.01 / financial advisors Georgia / face-to-face meeting', status: 'Scale', sent: 88, accepted: 33, cr: '37.5%', messages: 23, replies: 5, rr: '21.7%', scheduled: 0 },
    { id: 'w5-16', name: '22.01 / financial advisors CIS / face-to-face meeting', status: 'Top Performer', sent: 48, accepted: 20, cr: '41.7%', messages: 20, replies: 2, rr: '10.0%', scheduled: 0 },
    { id: 'w5-17', name: '28.01 / PBFO / Senior Relationship Managers / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 14, accepted: 2, cr: '14.3%', messages: 2, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w5-18', name: '28.01 / PBFO / Private Banker, Client Advisor / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 15, accepted: 2, cr: '13.3%', messages: 1, replies: 1, rr: '100.0%', scheduled: 0 },
    { id: 'w5-19', name: '30.01 / PBFO / executive director / Geneva, Zurich, Monaco, Luxembourg, Dubai--copy', status: 'Scale', sent: 4, accepted: 0, cr: '0.0%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
  ],
  'Week 6': [
    { id: 'w6-1', name: '21 nov / exBlackTower', status: 'Kill', sent: 0, accepted: 0, cr: '0.0%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w6-2', name: 'retarget /21 nov / exBlackTower', status: 'Scale', sent: 21, accepted: 1, cr: '4.8%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w6-3', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Scale', sent: 79, accepted: 31, cr: '39.2%', messages: 48, replies: 8, rr: '16.7%', scheduled: 2 },
    { id: 'w6-4', name: 'Saudi - Angel/private investors - 9.10 (linkedIn search)', status: 'Kill', sent: 1, accepted: 0, cr: '0.0%', messages: 1, replies: 1, rr: '100.0%', scheduled: 1 },
    { id: 'w6-5', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 23, accepted: 4, cr: '17.4%', messages: 12, replies: 2, rr: '16.7%', scheduled: 2 },
    { id: 'w6-6', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 89, accepted: 19, cr: '21.3%', messages: 45, replies: 4, rr: '8.9%', scheduled: 4 },
    { id: 'w6-7', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Top Performer', sent: 85, accepted: 39, cr: '45.9%', messages: 69, replies: 12, rr: '17.4%', scheduled: 0 },
    { id: 'w6-8', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 85, accepted: 19, cr: '22.4%', messages: 27, replies: 9, rr: '33.3%', scheduled: 1 },
    { id: 'w6-9', name: 'UAE - Angel investors - 2.10 (Dima\'s base)', status: 'Scale', sent: 49, accepted: 11, cr: '22.4%', messages: 23, replies: 3, rr: '13.0%', scheduled: 1 },
    { id: 'w6-10', name: 'exDeVereGroup - 19.08', status: 'Scale', sent: 34, accepted: 10, cr: '29.4%', messages: 11, replies: 2, rr: '18.2%', scheduled: 0 },
    { id: 'w6-11', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Scale', sent: 55, accepted: 10, cr: '18.2%', messages: 8, replies: 3, rr: '37.5%', scheduled: 3 },
    { id: 'w6-12', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Top Performer', sent: 14, accepted: 6, cr: '42.9%', messages: 10, replies: 2, rr: '20.0%', scheduled: 1 },
    { id: 'w6-13', name: '13.12 /South Africa / private investors', status: 'Scale', sent: 1, accepted: 0, cr: '0.0%', messages: 1, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w6-14', name: '22.01 / investors CIS / face-to-face meeting', status: 'Scale', sent: 197, accepted: 34, cr: '17.3%', messages: 38, replies: 10, rr: '26.3%', scheduled: 4 },
    { id: 'w6-15', name: '22.01 / investors Georgia / face-to-face meeting', status: 'Scale', sent: 32, accepted: 9, cr: '28.1%', messages: 27, replies: 7, rr: '25.9%', scheduled: 3 },
    { id: 'w6-16', name: '22.01 / financial advisors Georgia / face-to-face meeting', status: 'Top Performer', sent: 21, accepted: 9, cr: '42.9%', messages: 30, replies: 11, rr: '36.7%', scheduled: 3 },
    { id: 'w6-17', name: '22.01 / financial advisors CIS / face-to-face meeting', status: 'Scale', sent: 119, accepted: 47, cr: '39.5%', messages: 39, replies: 5, rr: '12.8%', scheduled: 0 },
    { id: 'w6-18', name: '28.01 / PBFO / Senior Relationship Managers / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 45, accepted: 15, cr: '33.3%', messages: 16, replies: 3, rr: '18.8%', scheduled: 0 },
    { id: 'w6-19', name: '28.01 / PBFO / Private Banker, Client Advisor / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 47, accepted: 15, cr: '31.9%', messages: 14, replies: 1, rr: '7.1%', scheduled: 0 },
    { id: 'w6-20', name: '30.01 / PBFO / executive director / Geneva, Zurich, Monaco, Luxembourg, Dubai--copy', status: 'Scale', sent: 69, accepted: 11, cr: '15.9%', messages: 10, replies: 1, rr: '10.0%', scheduled: 0 },
  ],
  'Week 7': [
    { id: 'w7-1', name: '12.02 / Wealth / Investment advisory / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 0, accepted: 0, cr: '0.0%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w7-2', name: 'retarget /21 nov / exBlackTower', status: 'Scale', sent: 48, accepted: 6, cr: '12.5%', messages: 7, replies: 1, rr: '14.3%', scheduled: 0 },
    { id: 'w7-3', name: '30.01 / PBFO / executive director / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 83, accepted: 27, cr: '32.5%', messages: 34, replies: 9, rr: '26.5%', scheduled: 1 },
    { id: 'w7-4', name: '28.01 / PBFO / Private Banker, Client Advisor / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 46, accepted: 11, cr: '23.9%', messages: 28, replies: 5, rr: '17.9%', scheduled: 0 },
    { id: 'w7-5', name: '28.01 / PBFO / Senior Relationship Managers / Geneva, Zurich, Monaco, Luxembourg, Dubai', status: 'Scale', sent: 75, accepted: 21, cr: '28.0%', messages: 34, replies: 8, rr: '23.5%', scheduled: 2 },
    { id: 'w7-6', name: '22.01 / investors CIS / face-to-face meeting', status: 'Scale', sent: 70, accepted: 25, cr: '35.7%', messages: 56, replies: 11, rr: '19.6%', scheduled: 4 },
    { id: 'w7-7', name: '22.01 / investors Georgia / face-to-face meeting', status: 'Scale', sent: 17, accepted: 4, cr: '23.5%', messages: 7, replies: 1, rr: '14.3%', scheduled: 1 },
    { id: 'w7-8', name: '22.01 / financial advisors Georgia / face-to-face meeting--copy', status: 'Kill', sent: 0, accepted: 0, cr: '0.0%', messages: 9, replies: 1, rr: '11.1%', scheduled: 3 },
    { id: 'w7-9', name: '22.01 / financial advisors CIS / face-to-face meeting', status: 'Scale', sent: 82, accepted: 32, cr: '39.0%', messages: 79, replies: 19, rr: '24.1%', scheduled: 2 },
    { id: 'w7-10', name: '13.12 / Indonesia - Malaysia / private investors', status: 'Scale', sent: 31, accepted: 5, cr: '16.1%', messages: 13, replies: 3, rr: '23.1%', scheduled: 0 },
    { id: 'w7-11', name: '13.12 / Qatar, Kuwait, Bahrain / private investors', status: 'Top Performer', sent: 3, accepted: 2, cr: '66.7%', messages: 9, replies: 1, rr: '11.1%', scheduled: 0 },
    { id: 'w7-12', name: '13.12 /South Africa / private investors', status: 'Kill', sent: 0, accepted: 0, cr: '0.0%', messages: 0, replies: 0, rr: '0.0%', scheduled: 0 },
    { id: 'w7-13', name: '21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer', status: 'Top Performer', sent: 37, accepted: 20, cr: '54.1%', messages: 49, replies: 17, rr: '34.7%', scheduled: 1 },
    { id: 'w7-14', name: 'Japan - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 3, accepted: 0, cr: '0.0%', messages: 5, replies: 2, rr: '40.0%', scheduled: 0 },
    { id: 'w7-15', name: 'Hong Kong - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 101, accepted: 20, cr: '19.8%', messages: 43, replies: 5, rr: '11.6%', scheduled: 0 },
    { id: 'w7-16', name: 'Singapore - Angel/private investors - 9.10 (linkedIn search)', status: 'Scale', sent: 103, accepted: 38, cr: '36.9%', messages: 66, replies: 9, rr: '13.6%', scheduled: 0 },
    { id: 'w7-17', name: 'UAE - Angel investors - 3.10 (linkedIn search)', status: 'Scale', sent: 98, accepted: 27, cr: '27.6%', messages: 33, replies: 8, rr: '24.2%', scheduled: 1 },
    { id: 'w7-18', name: 'UAE - Angel investors - 2.10 (Dima\'s base)', status: 'Scale', sent: 16, accepted: 5, cr: '31.3%', messages: 19, replies: 2, rr: '10.5%', scheduled: 0 },
    { id: 'w7-19', name: 'exDeVereGroup - 19.08', status: 'Top Performer', sent: 29, accepted: 12, cr: '41.4%', messages: 15, replies: 3, rr: '20.0%', scheduled: 0 },
  ],
};

export const allAccountMetrics: Record<string, AccountMetric[]> = {
  'Week 1': [
    { id: '1', name: 'Igor Smirnov', sent: 200, accepted: 65, messages: 81, replies: 19, scheduled: 0, maxSent: 210, efficiency: '95%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 31, accepted: 10, messages: 10, replies: 5, scheduled: 0, maxSent: 210, efficiency: '15%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 49, accepted: 17, messages: 19, replies: 4, scheduled: 0, maxSent: 175, efficiency: '28%', activity: 'Низкая активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 15, accepted: 1, messages: 0, replies: 0, scheduled: 0, maxSent: 60, efficiency: '25%', activity: 'Низкая активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 0, accepted: 0, messages: 0, replies: 0, scheduled: 0, maxSent: 132, efficiency: '0%', activity: 'Ограничение' },
  ],
  'Week 2': [
    { id: '1', name: 'Igor Smirnov', sent: 200, accepted: 90, messages: 116, replies: 29, scheduled: 3, maxSent: 210, efficiency: '95%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 36, accepted: 9, messages: 15, replies: 4, scheduled: 2, maxSent: 210, efficiency: '17%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 50, accepted: 10, messages: 19, replies: 3, scheduled: 0, maxSent: 175, efficiency: '29%', activity: 'Низкая активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 15, accepted: 1, messages: 1, replies: 0, scheduled: 0, maxSent: 60, efficiency: '25%', activity: 'Низкая активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 129, accepted: 22, messages: 19, replies: 2, scheduled: 0, maxSent: 132, efficiency: '98%', activity: 'Высокая активность' },
    { id: '6', name: 'Valentina Pedro', sent: 0, accepted: 0, messages: 0, replies: 0, scheduled: 0, maxSent: 125, efficiency: '0%', activity: 'Ограничение' },
  ],
  'Week 3': [
    { id: '1', name: 'Igor Smirnov', sent: 198, accepted: 62, messages: 128, replies: 28, scheduled: 6, maxSent: 210, efficiency: '94%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 30, accepted: 11, messages: 13, replies: 2, scheduled: 0, maxSent: 210, efficiency: '14%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 76, accepted: 31, messages: 37, replies: 9, scheduled: 0, maxSent: 175, efficiency: '43%', activity: 'Средняя активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 15, accepted: 1, messages: 1, replies: 0, scheduled: 0, maxSent: 60, efficiency: '25%', activity: 'Низкая активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 198, accepted: 30, messages: 39, replies: 11, scheduled: 1, maxSent: 225, efficiency: '88%', activity: 'Высокая активность' },
    { id: '6', name: 'Valentina Pedro', sent: 50, accepted: 14, messages: 13, replies: 3, scheduled: 0, maxSent: 125, efficiency: '40%', activity: 'Средняя активность' },
  ],
  'Week 4': [
    { id: '1', name: 'Igor Smirnov', sent: 199, accepted: 64, messages: 92, replies: 16, scheduled: 4, maxSent: 199, efficiency: '114%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 38, accepted: 12, messages: 14, replies: 3, scheduled: 0, maxSent: 199, efficiency: '10%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 50, accepted: 14, messages: 28, replies: 6, scheduled: 2, maxSent: 199, efficiency: '16%', activity: 'Ограничение' },
    { id: '4', name: 'Alexandra Nazarova', sent: 19, accepted: 9, messages: 4, replies: 1, scheduled: 0, maxSent: 199, efficiency: '11%', activity: 'Низкая активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 189, accepted: 35, messages: 34, replies: 7, scheduled: 3, maxSent: 199, efficiency: '77%', activity: 'Средняя активность' },
    { id: '6', name: 'Valentina Pedro', sent: 0, accepted: 0, messages: 0, replies: 0, scheduled: 1, maxSent: 199, efficiency: '0%', activity: 'замена' },
  ],
  'Week 5': [
    { id: '1', name: 'Igor Smirnov', sent: 161, accepted: 70, messages: 151, replies: 38, scheduled: 7, maxSent: 105, efficiency: '153%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 21, accepted: 5, messages: 13, replies: 4, scheduled: 0, maxSent: 150, efficiency: '14%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 31, accepted: 11, messages: 24, replies: 6, scheduled: 0, maxSent: 240, efficiency: '13%', activity: 'Низкая активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 26, accepted: 7, messages: 16, replies: 3, scheduled: 2, maxSent: 50, efficiency: '52%', activity: 'Средняя активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 195, accepted: 65, messages: 93, replies: 25, scheduled: 2, maxSent: 6, efficiency: '3250%', activity: 'Высокая активность' },
    { id: '6', name: 'Chloé Boutiguila', sent: 60, accepted: 9, messages: 7, replies: 2, scheduled: 0, maxSent: 90, efficiency: '67%', activity: 'Средняя активность' },
    { id: '7', name: 'Ruslan Pshenin', sent: 200, accepted: 58, messages: 32, replies: 5, scheduled: 0, maxSent: 125, efficiency: '160%', activity: 'Высокая активность' },
    { id: '8', name: 'Olga Yatchenya', sent: 19, accepted: 4, messages: 3, replies: 1, scheduled: 0, maxSent: 50, efficiency: '38%', activity: 'Средняя активность' },
  ],
  'Week 6': [
    { id: '1', name: 'Igor Smirnov', sent: 189, accepted: 67, messages: 150, replies: 33, scheduled: 7, maxSent: 150, efficiency: '126%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 25, accepted: 8, messages: 8, replies: 3, scheduled: 0, maxSent: 0, efficiency: '0%', activity: 'Ограничение' },
    { id: '3', name: 'Elena Smirnova', sent: 90, accepted: 33, messages: 27, replies: 3, scheduled: 0, maxSent: 100, efficiency: '90%', activity: 'Высокая активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 56, accepted: 13, messages: 21, replies: 4, scheduled: 1, maxSent: 75, efficiency: '75%', activity: 'Средняя активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 192, accepted: 52, messages: 82, replies: 13, scheduled: 6, maxSent: 180, efficiency: '107%', activity: 'Ограничение' },
    { id: '6', name: 'Chloé Boutiguila', sent: 121, accepted: 40, messages: 37, replies: 8, scheduled: 2, maxSent: 150, efficiency: '81%', activity: 'Высокая активность' },
    { id: '7', name: 'Ruslan Pshenin', sent: 231, accepted: 58, messages: 102, replies: 32, scheduled: 9, maxSent: 100, efficiency: '231%', activity: 'Высокая активность' },
    { id: '8', name: 'Olga Yatchenya', sent: 162, accepted: 38, messages: 33, replies: 2, scheduled: 0, maxSent: 90, efficiency: '180%', activity: 'Высокая активность' },
    { id: '9', name: 'Nikita Napolnikov', sent: 0, accepted: 0, messages: 0, replies: 0, scheduled: 0, maxSent: 0, efficiency: '0%', activity: 'На прогреве' },
  ],
  'Week 7': [
    { id: '1', name: 'Igor Smirnov', sent: 197, accepted: 74, messages: 123, replies: 31, scheduled: 1, maxSent: 140, efficiency: '141%', activity: 'Высокая активность' },
    { id: '2', name: 'Andrey Tsvetkov', sent: 51, accepted: 20, messages: 17, replies: 2, scheduled: 0, maxSent: 5, efficiency: '1020%', activity: 'Высокая активность' },
    { id: '3', name: 'Elena Smirnova', sent: 28, accepted: 20, messages: 36, replies: 9, scheduled: 0, maxSent: 3, efficiency: '933%', activity: 'Высокая активность' },
    { id: '4', name: 'Alexandra Nazarova', sent: 51, accepted: 10, messages: 21, replies: 5, scheduled: 1, maxSent: 4, efficiency: '1275%', activity: 'Высокая активность' },
    { id: '5', name: 'Roman Vashkevich', sent: 25, accepted: 29, messages: 72, replies: 16, scheduled: 3, maxSent: 5, efficiency: '500%', activity: 'Высокая активность' },
    { id: '6', name: 'Chloé Boutiguila', sent: 186, accepted: 57, messages: 88, replies: 23, scheduled: 0, maxSent: 150, efficiency: '124%', activity: 'Высокая активность' },
    { id: '7', name: 'Ruslan Pshenin', sent: 159, accepted: 60, messages: 105, replies: 25, scheduled: 7, maxSent: 5, efficiency: '3180%', activity: 'Высокая активность' },
    { id: '8', name: 'Olga Yatchenya', sent: 145, accepted: 38, messages: 73, replies: 13, scheduled: 3, maxSent: 180, efficiency: '81%', activity: 'Высокая активность' },
    { id: '9', name: 'Nikita Napolnikov', sent: 0, accepted: 0, messages: 0, replies: 0, scheduled: 0, maxSent: 4, efficiency: '0%', activity: 'На прогреве' },
  ]
};

export const leads: Lead[] = [
  {
    "id": "week2-l1",
    "weekId": "Week 2",
    "name": "Manuel Hadj-Rahmoun",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQGQw_86Y6uKcg/profile-displayphoto-crop_800_800/B56Zr2Uv5nHQAI-/0/1765069226432?e=1769644800&v=beta&t=4OWJURYUCQq5N1iZ9OyfDY7nW0kYhqvsU0PcpWWgP7Q",
    "company": "ARES",
    "role": "Founder",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "05.01",
    "dateConducted": "Week 3",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/manuelhr",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "week2-l2",
    "weekId": "Week 2",
    "name": "Edwin John",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQFC8JNXNVHqvg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1723393264108?e=1769644800&v=beta&t=wkTbcjbe_MjiZhptapHHH_YDQ1fQJijDbVcRWJDoS3M",
    "company": "Mumbai Angels",
    "role": "Venture Capital Advocate",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "05.01",
    "dateConducted": "Week 2",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/edwin-john-10a78051",
    "comment": "",
    "campaign": "UAE - Angel investors - 2.10 (Dima's base)"
  },
  {
    "id": "week2-l3",
    "weekId": "Week 2",
    "name": "Iuliia Skriaga",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQFDm-UVhB_cnw/profile-displayphoto-crop_800_800/B4DZjTHz21H4AQ-/0/1755888698648?e=1769644800&v=beta&t=OeabtLwPyyX4_uEHahksNLJ6V_2G996l02Pm5GcfmHE",
    "company": "3S Money",
    "role": "Sales Operations Analyst",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "07.01",
    "dateConducted": "Week 3",
    "account": "Andrey Tsvetkov",
    "linkedin": "https://linkedin.com/in/iuliia-skriaga-90257b215",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "week2-l4",
    "weekId": "Week 2",
    "name": "Faisal Mahmood",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQHnn_xGe6IxOA/profile-displayphoto-crop_800_800/B4DZuPoLfXIYAM-/0/1767641234284?e=1769644800&v=beta&t=9AsLoc06aZsqUV4eZzHnbwWUr5hfrmkqZ7Uiof7Pyf4",
    "company": "Bahrain Economic Development Board",
    "role": "Investment Development Department",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "08.01",
    "dateConducted": "Week 3",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/faisal-mahmood-msf-2b0011b5",
    "comment": "",
    "campaign": "13.12 / Qatar, Kuwait, Bahrain / private investors"
  },
  {
    "id": "week2-l5",
    "weekId": "Week 2",
    "name": "Scott Fletcher",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQEbYCOsHQ6_sw/profile-displayphoto-crop_800_800/B4DZh7AxG8GsAU-/0/1754410456145?e=1769644800&v=beta&t=-FmzwdLaZC5PPoqZg6og5YxHUiRZBM4Bo0SwqSG_LhI",
    "company": "FETCH",
    "role": "Investor and None Exec Chairman",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "09.01",
    "dateConducted": "Week 3",
    "account": "Andrey Tsvetkov",
    "linkedin": "https://linkedin.com/in/scott-fletcher-mbe-223795158",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "week3-l6",
    "weekId": "Week 3",
    "name": "Mazen Khatib",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRZkZZE7nNj7nSZg06UikhCX0xORyTYV1RW99dbn9PI4-STFw",
    "company": "M7 Capital",
    "role": "Chief Investment Officer",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "12.01",
    "dateConducted": "Week 3",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/mazen-khatib-329b341",
    "comment": "",
    "campaign": "13.12 / Qatar, Kuwait, Bahrain / private investors"
  },
  {
    "id": "week3-l7",
    "weekId": "Week 3",
    "name": "Anastasiia Piven",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9QgZnHu_d3ifNxy9TXUDFq12aFO1i955Oirmt8DOP5UcVcg",
    "company": "KHK & Partners Limited",
    "role": "Investment Operations",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "12.01",
    "dateConducted": "Week 3",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/anastasiia-piven-24615921b",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "week3-l8",
    "weekId": "Week 3",
    "name": "Eng Nayef Aljebreen",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSYs5KmP56n_HUeqlIzApGY1Rgvee-43CyQWlGM7BtPNO-lqg",
    "company": "Uni-Ventures",
    "role": "Founder & CEO",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "12.01",
    "dateConducted": "",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/nayefa",
    "comment": "",
    "campaign": "Saudi - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "week3-l9",
    "weekId": "Week 3",
    "name": "Nauman Abdal",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSAn-gXH7eIbCtrPqItWky1ECu7som14Kgf9MYhMcPGRHIc7Q",
    "company": "Unifrutti Group",
    "role": "Head of Treasury & Investor Relations",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "12.01",
    "dateConducted": "Week 3",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/naumanabdal",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "week3-l12",
    "weekId": "Week 3",
    "name": "Leonard Belinga",
    "photo": "https://ui-avatars.com/api/?name=Leonard+Belinga&background=0D8ABC&color=fff",
    "company": "venture capitalist",
    "role": "Private Investor",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "15.01",
    "dateConducted": "",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/leonard-belinga-17bb1720b",
    "comment": "",
    "campaign": "13.12 /South Africa / private investors"
  },
  {
    "id": "w5-l1",
    "weekId": "Week 5",
    "name": "Freedom Magwaza",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMMepxr1LZY8XjWNrh3zNAakyrGbGeegbPkvQA4NNdlnsv7A",
    "company": "SPEED POWER ENTERPRISE",
    "role": "PRIVATE INVESTOR",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "19.01",
    "dateConducted": "January",
    "account": "Elena Smirnova",
    "linkedin": "https://linkedin.com/in/freedom-magwaza-66369b125",
    "comment": "",
    "campaign": "13.12 /South Africa / private investors"
  },
  {
    "id": "w5-l2",
    "weekId": "Week 5",
    "name": "David Susanto",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyQIMCqtfEBin6CzhflvF0rcXTIwpJaqFM77-Jt1r5m9-uyw",
    "company": "Zia Guild",
    "role": "Guild Master",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "19.02",
    "dateConducted": "January",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/davidsusanto",
    "comment": "",
    "campaign": "13.12 / Indonesia - Malaysia / private investors"
  },
  {
    "id": "w5-l3",
    "weekId": "Week 5",
    "name": "Anshul Agrawal",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQGfIIcPeIRJMA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1692783087970?e=1770854400&v=beta&t=Ee0VCdmsoL986Nmftt473uW2ON80T0CXtnV1LeH9zBI",
    "company": "Imdaad Group",
    "role": "Energy Auditor",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "20.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/anshul-agrawal-047a17b3",
    "comment": "",
    "campaign": "Singapore - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w5-l4",
    "weekId": "Week 5",
    "name": "Mohammad Jamal",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQHjTcPQI8LvnA/profile-displayphoto-shrink_800_800/B4DZrPZ47zJcAc-/0/1764416262375?e=1770854400&v=beta&t=B_remayj7v-_WvQUSk6waubH7RkdTdAlQr24W0Kgzyc",
    "company": "Business Angels of Qatar",
    "role": "Angel Investor",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "20.01",
    "dateConducted": "January",
    "account": "Valentina Pedro",
    "linkedin": "https://linkedin.com/in/mohammad-malek-al-jamal-cfa-45058871",
    "comment": "",
    "campaign": ""
  },
  {
    "id": "w5-l5",
    "weekId": "Week 5",
    "name": "Martin Glimmerholm",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBEL5p6h3upkbMheqBGWasrM78b6lJiMfSEcXYG9Al3AbnjQ",
    "company": "Self-Employed",
    "role": "Senior advisor – independent",
    "quality": 5,
    "status": "Встреча состоялась",
    "dateScheduled": "20.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/martin-glimmerholm-385a5925",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w5-l6",
    "weekId": "Week 5",
    "name": "Tshepo Motlhetlhi",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpL1H8LPDavG5H8Hn0O8hOI8qYfSdQ0Yfn3JgVsWINJbAhfQ",
    "company": "Alterra Capital Partners",
    "role": "Private Equity Investor",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "20.01",
    "dateConducted": "January",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/tshepo-motlhetlhi-55b68a53",
    "comment": "",
    "campaign": "13.12 /South Africa / private investors"
  },
  {
    "id": "w5-l7",
    "weekId": "Week 5",
    "name": "Ilya Kazakov",
    "photo": "https://media.licdn.com/dms/image/v2/C4D03AQGGJ96uFUH0hQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1656319869289?e=1770854400&v=beta&t=p4xv9fcgxTlZ6xatDaLIKpaFRnLEVDF4wT4NOrHARRM",
    "company": "D360 Bank",
    "role": "Head of Risk Modeling & Analytics",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "21.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/ilyaka",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w5-l8",
    "weekId": "Week 5",
    "name": "Grace Yun Xia",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ61RSsxtUHHh-lCrdqYoAJ0IDvVR8yDXBfKWwV8KoJBKi_VA",
    "company": "xAI",
    "role": "Investor",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "22.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/graceyunxia",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w5-l9",
    "weekId": "Week 5",
    "name": "Chrissy H.",
    "photo": "https://ui-avatars.com/api/?name=Chrissy+H.&background=0D8ABC&color=fff",
    "company": "Reimagine X Studio",
    "role": "Investor & Founder & Creative Designer",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "22.01",
    "dateConducted": "January",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/chrissy-huang",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w5-l10",
    "weekId": "Week 5",
    "name": "Anwar Al-Yahya",
    "photo": "https://ui-avatars.com/api/?name=Anwar+Al-Yahya&background=0D8ABC&color=fff",
    "company": "Kuwait Finance House",
    "role": "Executive Manager",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "23.01",
    "dateConducted": "January",
    "account": "Elena Smirnova",
    "linkedin": "https://linkedin.com/in/anwar-hamad-al-yahya-80122826",
    "comment": "",
    "campaign": "13.12 / Qatar, Kuwait, Bahrain / private investors"
  },
  {
    "id": "w5-l11",
    "weekId": "Week 5",
    "name": "Aman Kumar Soran",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSz6d7KlIuXNy-EtR01nEU2XTqBaRhunyd-fAF1SE6ci4x4hQ",
    "company": "SBI Investment",
    "role": "Venture Capitalist",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "14.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/aman-kumar-soran",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w5-l12",
    "weekId": "Week 5",
    "name": "Ilya Etko",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRtRJtLtDlOFzUhwGxTeLhTxtWSkydAb3kZHBS_7lD5wQTcFA",
    "company": "International Strategic Holding",
    "role": "Chief Strategy Officer",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "15.01",
    "dateConducted": "January",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/ilyaetko",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w6-l1",
    "weekId": "Week 6",
    "name": "Angeline Siow",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTFqX8gBzk1adE8lOOA_UyzdECmIhythMgkiXzPL8lNRfV3fg",
    "company": "Grasshopper",
    "role": "Investor Relations Associate",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/angeline-siow-139a521b8",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l2",
    "weekId": "Week 6",
    "name": "Carly Bunni",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQHOlQvD7xLJUw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1724582255103?e=1772064000&v=beta&t=AKH7SIRqWwcfrvS7j0nfIJOFi0_YgwolnmcUX6ovYUY",
    "company": "Ardian",
    "role": "Investor Relations",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/carly-bunni-0845a9211",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "w6-l3",
    "weekId": "Week 6",
    "name": "Ts. T. (Zehan Teoh)",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQEMviLy__6crA/profile-displayphoto-crop_800_800/B56ZvAyUIxIoAI-/0/1768465977926?e=1772064000&v=beta&t=RAeeqlVs0-FHAYCaCIcg17gGBScG0kf5VDuGvlbg1yQ",
    "company": "Finsall Resources",
    "role": "Angel Investor",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/zehant",
    "comment": "",
    "campaign": "13.12 / Indonesia - Malaysia / private investors"
  },
  {
    "id": "w6-l4",
    "weekId": "Week 6",
    "name": "Jon I. Bergsteinsson",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcROueDnNKLdIxijzE9Y8BrIVbSBq1F5F83Ws9eSdwTB4DHNeA",
    "company": "Stealth Mode",
    "role": "Voice of MedTech | Industry Truth-Teller | MP @ LIFA.VC | Chair of IceBAN",
    "quality": null,
    "status": "отмена",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/joningib",
    "comment": "",
    "campaign": "UAE - Angel investors - 2.10 (Dima's base)"
  },
  {
    "id": "w6-l5",
    "weekId": "Week 6",
    "name": "Matthew Baum",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQEoeT3_LNAZXA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1691107914680?e=1772064000&v=beta&t=5-0_9lUwwX0D9KwGQtMuJt5GNydXRZvTQD385x6N79s",
    "company": "CBC Group",
    "role": "Associate - Investor Relations",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/matthew-baum-972354150",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l6",
    "weekId": "Week 6",
    "name": "Ali Janahi",
    "photo": "https://media.licdn.com/dms/image/v2/D4E03AQEkMtPzj_-1Hw/profile-displayphoto-shrink_800_800/B4EZVGdc0tHUAc-/0/1740643881957?e=1772064000&v=beta&t=f1d0QxNdGgjQ_XwBRE1buRGG4waWbWU0hoV9BL-YeY0",
    "company": "National Bank of Bahrain",
    "role": "Head of Wealth Management",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "3.02",
    "dateConducted": "February",
    "account": "Chloé Boutiguila",
    "linkedin": "https://linkedin.com/in/ali-janahi-557719188",
    "comment": "",
    "campaign": "13.12 / Qatar, Kuwait, Bahrain / private investors"
  },
  {
    "id": "w6-l7",
    "weekId": "Week 6",
    "name": "Ryаn Othmаn",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQGHQid2zbhqag/profile-displayphoto-crop_800_800/B56ZkAPPJvHkAU-/0/1756645619115?e=1772064000&v=beta&t=OZuMT4azujI1wdm9R_9G6vnq70F_cI69ErcOCjPKzME",
    "company": "MNO Partners",
    "role": "Founding Partner - Real Estate Development",
    "quality": null,
    "status": "не отвечает",
    "dateScheduled": "3.02",
    "dateConducted": "February",
    "account": "Alexandra Nazarova",
    "linkedin": "https://linkedin.com/in/ryan-othman",
    "comment": "",
    "campaign": "Saudi - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l8",
    "weekId": "Week 6",
    "name": "Talifa Isgandar",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7aK6EnNxNedQWzX8_USInIQ4Qp2S2lYdwVB62BRPKa3TeLw",
    "company": "SABAH.HUB",
    "role": "Board Member",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/talifa-isgandar-459910192",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w6-l9",
    "weekId": "Week 6",
    "name": "David Tushishvili",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS9VwhVaP9ANe88CNF0wcoh69hGGpu4VJ83OuC4UhoM3SsNMw",
    "company": "Blockberg",
    "role": "Advisory Board Member",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/davidtushishvili",
    "comment": "",
    "campaign": "22.01 / investors Georgia / face-to-face meeting"
  },
  {
    "id": "w6-l10",
    "weekId": "Week 6",
    "name": "Tornike Revishvili",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRWlaFeJhOKencYhjTt31rKx8SiaDpfjaXXFzRIMq2Iscm3NA",
    "company": "Skyward Solutions",
    "role": "Chief Operating Officer",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/tornike-revishvili-a28b7899",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w6-l11",
    "weekId": "Week 6",
    "name": "Shin Ito",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTogcrMFc-w0oYCaXYQmxziTyx1UjEJrIMxopWRJ2rEX-TQHQ",
    "company": "",
    "role": "Founder, CEO & Representative Director at iKoyoo, Inc.",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/shinito123",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l12",
    "weekId": "Week 6",
    "name": "Mikha Tamasidze",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRdpg2x_qhLT_rNR7JsKadLTGTUMuFW00-zzuJfgDKiJiA-uw",
    "company": "Anko",
    "role": "Chief Financial Officer",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/mikha-tamasidze-924191182",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w6-l13",
    "weekId": "Week 6",
    "name": "Vahagn Mughnetsyan",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQdwku6KO0LmgSOA6eHUaQliimgtQBS9geoWISvdIVRwwwEqg",
    "company": "Enterprise Armenia",
    "role": "Head of Investor Support and Aftercare Service Department",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/vahagnmughnetsyan",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w6-l14",
    "weekId": "Week 6",
    "name": "Nikoloz Alavidze",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS1G-E5PFRN-tJqeBJm1od-Zthn7HdWuRGFFJjLR8dLwAMW9w",
    "company": "Impact Fund Actio",
    "role": "Actio Impact Fund Impact investor",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/nikoloz-alavidze-85629843",
    "comment": "",
    "campaign": "22.01 / investors Georgia / face-to-face meeting"
  },
  {
    "id": "w6-l15",
    "weekId": "Week 6",
    "name": "Ari Arjoto",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcReDstNPsz7R1DtlTfw9xHdX7HvLK8jumRoUrap6_RhENnfeA",
    "company": "Nusa teknogra indonesia",
    "role": "Private Investor",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/ari-yohan-arjoto-3b3396395",
    "comment": "",
    "campaign": "13.12 / Indonesia - Malaysia / private investors"
  },
  {
    "id": "w6-l16",
    "weekId": "Week 6",
    "name": "Pradipta Mullick",
    "photo": "https://media.licdn.com/dms/image/v2/C5603AQFEGDl9YaNF4A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1632818586180?e=1772064000&v=beta&t=t6msaKECm9jdym_LkC6gp6Ad8xdHfpuJKlnZ8tn5-mw",
    "company": "Intertran Technology",
    "role": "COO, Managing Director",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Chloé Boutiguila",
    "linkedin": "https://linkedin.com/in/pradiptamullick",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l17",
    "weekId": "Week 6",
    "name": "Brenda Ng",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS_0nWCKEjtyrfT26j6cPYt1BgAp_lMLuYSkKR8-vonZGOn8w",
    "company": "The Facilitators' Project",
    "role": "Chief Fun(d) Officer (CFO)",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/brenda-ng-3b391922",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l18",
    "weekId": "Week 6",
    "name": "Giorgi Kasradze",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQGt--M7VWu9tg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1679464564799?e=1772064000&v=beta&t=4XMunX4dKBCsL9JV3pk0MeFGWnXl6B6_Y51h4HisPu4",
    "company": "",
    "role": "CEO @ ELT Building | MBA, Corporate Finance",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/giorgi-kasradze-7627244",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w6-l19",
    "weekId": "Week 6",
    "name": "Zhibek Karamanova",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSebXF1Ew34dzcwESQRERI-yGTVm12G8qaXhV_6Bu9McvhsmA",
    "company": "Keremet Real Estate LLP",
    "role": "Founder",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/zhibek-karamanova-6768a05",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w6-l20",
    "weekId": "Week 6",
    "name": "Georgy Grib",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXEOpluWg98eaL7061pVkXPPcAbtKzOokuWUVBfS73xygxTA",
    "company": "Tech Horizons Venture",
    "role": "Venture Studio Consultant",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/georgy-grib-187b884",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w6-l21",
    "weekId": "Week 6",
    "name": "Karan Pawani",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTTstw2PaWXdq0J9a0C2fw3qRqE6FqzuhaBL5Qt3Z4V5Uz1DQ",
    "company": "Silverdale Capital Pte Ltd",
    "role": "Investor Relations Associate",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/karan-pawani",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w6-l22",
    "weekId": "Week 6",
    "name": "Any Widjaja",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSUvsah25ecpKMnXblo3M822AAoVTj_YrQidNG2OzHMi6POgQ",
    "company": "Festive Fields Entertainment",
    "role": "Investor",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/any-luvena-widjaja-33220a269",
    "comment": "",
    "campaign": "13.12 / Indonesia - Malaysia / private investors"
  },
  {
    "id": "w6-l23",
    "weekId": "Week 6",
    "name": "Konstantin Shevchenko",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu55J9UAJKvYGC7RtuiW_5HBCLxyEHLNMqOmymTScwxoe7ZQ",
    "company": "\"Waterfall View\" LLC",
    "role": "Owner’s Representative (Land Sale & Development)",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/konstantin-shevchenko-77351b31",
    "comment": "",
    "campaign": "22.01 / investors Georgia / face-to-face meeting"
  },
  {
    "id": "w6-l24",
    "weekId": "Week 6",
    "name": "Evgenia Zarubin",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTvd8G55m3eY9ocqKlQo557_NMN4p73ExknvDDte5N3V4bTzw",
    "company": "Core Realty Accosiates Inc",
    "role": "номер передан Саше",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/evgenia-zarubin",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w6-l25",
    "weekId": "Week 6",
    "name": "Maria Erokhina",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRXAKiT50wgYMuR34M6aFPXPzlOuvCwYJjuP4mUpDZoF7O-TQ",
    "company": "JSC Sberbank",
    "role": "Executive Director, Project manager",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/maria-erokhina-850303345",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w6-l26",
    "weekId": "Week 6",
    "name": "Talha A.",
    "photo": "https://ui-avatars.com/api/?name=Talha+A.&background=0D8ABC&color=fff",
    "company": "Self-Employed",
    "role": "Crypto investor and blockchain data analyst",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "27.01",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/talha-a-aab136bb",
    "comment": "",
    "campaign": "13.12 / Qatar, Kuwait, Bahrain / private investors"
  },
  {
    "id": "w6-l27",
    "weekId": "Week 6",
    "name": "Maté Z.",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQEfHZ0MT_5eQA/profile-displayphoto-crop_800_800/B56Znj7KNcI8AI-/0/1760465560739?e=1771459200&v=beta&t=DwD99a5o8cdZlFtRLdlbdEH5xBQ1zgPlImSmr86Z6W4",
    "company": "Various Startups",
    "role": "Startup Advisor | Angel Investor",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "29.01",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/matezgombic",
    "comment": "",
    "campaign": "UAE - Angel investors - 2.10 (Dima's base)"
  },
  {
    "id": "w6-l28",
    "weekId": "Week 6",
    "name": "Ayla Mironova",
    "photo": "https://media.licdn.com/dms/image/v2/D4E03AQGTtXzEjgs3AA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1700167090395?e=1771459200&v=beta&t=rWM6MtwSW9a4PDVOtAg7e4c7UAB-LH1ZBA7wdBkQdJc",
    "company": "AI-Bridge/Below Technologies",
    "role": "Chief Financial Officer, CBDO",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "30.01",
    "dateConducted": "February",
    "account": "Alexandra Nazarova",
    "linkedin": "https://linkedin.com/in/aylamironova",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w7-l1",
    "weekId": "Week 7",
    "name": "Evgenia Zarubin",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTvd8G55m3eY9ocqKlQo557_NMN4p73ExknvDDte5N3V4bTzw",
    "company": "Core Realty Accosiates Inc",
    "role": "номер передан Саше",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/evgenia-zarubin",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w7-l2",
    "weekId": "Week 7",
    "name": "Maria Erokhina",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRXAKiT50wgYMuR34M6aFPXPzlOuvCwYJjuP4mUpDZoF7O-TQ",
    "company": "JSC Sberbank",
    "role": "Executive Director, Project manager",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/maria-erokhina-850303345",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w7-l3",
    "weekId": "Week 7",
    "name": "Nikoloz Shurgaia",
    "photo": "https://ui-avatars.com/api/?name=Nikoloz+Shurgaia&background=0D8ABC&color=fff",
    "company": "Various Companies",
    "role": "Management Consultant",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "9.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/nikoloz-shurgaia-4b011a",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w7-l4",
    "weekId": "Week 7",
    "name": "Irina I.",
    "photo": "https://media.licdn.com/dms/image/v2/D4D35AQFSUEVl5WMFQg/profile-framedphoto-shrink_800_800/B4DZrp2hEpIAAg-/0/1764859974316?e=1771851600&v=beta&t=lDQJCgN_ArqpR9x6GxCAQrrZc35KQ0t62rHo811NRnQ",
    "company": "Unreal Nova Academy",
    "role": "Founder",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "9.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/irina-i-60b77a10a",
    "comment": "",
    "campaign": "22.01 / investors Georgia / face-to-face meeting"
  },
  {
    "id": "w7-l5",
    "weekId": "Week 7",
    "name": "Askar Toksanbayev",
    "photo": "https://media.licdn.com/dms/image/v2/D5603AQFZoC5-GSsVRQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1706778040515?e=1772668800&v=beta&t=Aj__p7eKjZIa9hHc3gZMwuVjlrvEUyR2yQ3jRkSEC1M",
    "company": "AT Finconsult",
    "role": "Founder and CEO",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "9.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/askartoxanbayev",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l6",
    "weekId": "Week 7",
    "name": "Ramprabu Chennakesavan",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLFN8qqxh2EvaEna42yl15_2EN5xa8eRupKFXKtMGOTM6Jpg",
    "company": "RAGHAV CONTRACTING LLC",
    "role": "Executive Director",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "9.02",
    "dateConducted": "February",
    "account": "Alexandra Nazarova",
    "linkedin": "https://linkedin.com/in/ramprabu",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "w7-l7",
    "weekId": "Week 7",
    "name": "Hashim Bakuvi",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQHVTxU_WeSl5A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1726566877252?e=1772668800&v=beta&t=sgO2I-18ISs2TNAyJN6OUcCGssYxDLcDhi6RXfd8SqI",
    "company": "Joygame Publishing",
    "role": "Partner",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "10.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/hashim82",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l8",
    "weekId": "Week 7",
    "name": "Aleksey Klementyev",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQFTptIaRHVZDw/profile-displayphoto-shrink_800_800/B4DZUP2LQAGkAk-/0/1739727616031?e=1772668800&v=beta&t=beP6J7a4kAbI-fuIEws1cUpYqs40kJ-bJmvz6o-R84U",
    "company": "Uniconf",
    "role": "Senior Finance Business Partner",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "10.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/aleksey-klementyev",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w7-l9",
    "weekId": "Week 7",
    "name": "Nino Putkaradze",
    "photo": "https://media.licdn.com/dms/image/v2/D4E03AQG0KCcqTzpMqg/profile-displayphoto-crop_800_800/B4EZo_Ihu1IQAI-/0/1761995791747?e=1772668800&v=beta&t=kLRNXOdSoMRjo6DXiA19NJEs9kOQ6dH89S04KiAD_kk",
    "company": "ideal smile",
    "role": "finance",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "10.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/nino-putkaradze-42928a397",
    "comment": "",
    "campaign": "22.01 / financial advisors Georgia / face-to-face meeting--copy"
  },
  {
    "id": "w7-l10",
    "weekId": "Week 7",
    "name": "Mehman Abbas",
    "photo": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSywgEiRmTGvwJFsuG_4piMAqs3u5uf-VYPqVOZNsW0ag5izg",
    "company": "ADB Ventures",
    "role": "Investment Advisory",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "11.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/mehman-a-abbas-54251aa",
    "comment": "",
    "campaign": "22.01 / financial advisors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l11",
    "weekId": "Week 7",
    "name": "Islam Kullarov",
    "photo": "https://media.licdn.com/dms/image/v2/D4E35AQFk368ecEf-zA/profile-framedphoto-shrink_800_800/B4EZiYyYIcHIAk-/0/1754909999950?e=1771851600&v=beta&t=0OcTNfpQKcQ-o3hs5oJvuXEbCAmnOQ8Yhnkt6uwpDio",
    "company": "Turkmenline",
    "role": "ES \"At-abray\" Head of legal and financial issues",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "12.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/islam-kullarov-c-a-p",
    "comment": "",
    "campaign": "22.01 / financial advisors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l12",
    "weekId": "Week 7",
    "name": "Alexander Lapshin",
    "photo": "https://ui-avatars.com/api/?name=Alexander+Lapshin&background=0D8ABC&color=fff",
    "company": "Sistema",
    "role": "Executive Director",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "12.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/alapshin",
    "comment": "",
    "campaign": "21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer"
  },
  {
    "id": "w7-l13",
    "weekId": "Week 7",
    "name": "Felipe Forero",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTkPnGPvucEJKtLKHuiS5_x6F2rJeAkutDDelkbsU2gD1OtAw",
    "company": "Vontobel",
    "role": "Private Banker",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "12.02",
    "dateConducted": "February",
    "account": "Olga Yatchenya",
    "linkedin": "https://linkedin.com/in/felipe-castaneda-forero-70b21645",
    "comment": "",
    "campaign": "30.01 / PBFO / executive director / Geneva, Zurich, Monaco, Luxembourg, Dubai"
  },
  {
    "id": "w7-l14",
    "weekId": "Week 7",
    "name": "Dina Mamytkulova",
    "photo": "https://media.licdn.com/dms/image/v2/C4D03AQGRGldb1F1R0w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1571635982124?e=1772668800&v=beta&t=CtYsP5RAahtL1PLM-TM0DjtdSGR2Z_HERdeomCof-x8",
    "company": "AIFC",
    "role": "Chief Corporate and Institutional Investors Officer",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "13.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/dina-mamytkulova-5b391a70",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l15",
    "weekId": "Week 7",
    "name": "Elchin Ismayilov",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQGXcJFVE3ub8g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1708988226272?e=1772668800&v=beta&t=eP5q5LthZRgfAjgFgMoKqEBysWcVTuNUys6-e6c0o5g",
    "company": "Elchin Ismayilov M.E",
    "role": "Innovation Consultant",
    "quality": null,
    "status": "личная встреча",
    "dateScheduled": "13.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/elchin-ismayil",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l16",
    "weekId": "Week 7",
    "name": "Muhammad Iqbal",
    "photo": "https://media.licdn.com/dms/image/v2/C5103AQFAmuOYfT685g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1569167756489?e=1772668800&v=beta&t=zjFOzsKRJE7fsGFREgqoqtHX_GpQs8zgooyqhJGH1mk",
    "company": "ADIB - Abu Dhabi Islamic Bank",
    "role": "Senior Relationship Manager, Business Banking",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "13.02",
    "dateConducted": "February",
    "account": "Olga Yatchenya",
    "linkedin": "https://linkedin.com/in/muhammad-sajid-iqbal-bb201824",
    "comment": "",
    "campaign": "28.01 / PBFO / Senior Relationship Managers / Geneva, Zurich, Monaco, Luxembourg, Dubai"
  },
  {
    "id": "w7-l17",
    "weekId": "Week 7",
    "name": "Mir Hussain",
    "photo": "https://ui-avatars.com/api/?name=Mir+Hussain&background=0D8ABC&color=fff",
    "company": "RAKBANK",
    "role": "Associate Vice President and Senior Relationship Manager",
    "quality": null,
    "status": "Запланирована",
    "dateScheduled": "13.02",
    "dateConducted": "February",
    "account": "Olga Yatchenya",
    "linkedin": "https://linkedin.com/in/mir-meesam-hussain-72523753",
    "comment": "",
    "campaign": "28.01 / PBFO / Senior Relationship Managers / Geneva, Zurich, Monaco, Luxembourg, Dubai"
  },
  {
    "id": "w7-l18",
    "weekId": "Week 7",
    "name": "Georgy Grib",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXEOpluWg98eaL7061pVkXPPcAbtKzOokuWUVBfS73xygxTA",
    "company": "Tech Horizons Venture",
    "role": "Venture Studio Consultant",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "6.02",
    "dateConducted": "February",
    "account": "Ruslan Pshenin",
    "linkedin": "https://linkedin.com/in/georgy-grib-187b884",
    "comment": "",
    "campaign": "22.01 / investors CIS / face-to-face meeting"
  },
  {
    "id": "w7-l19",
    "weekId": "Week 7",
    "name": "Ari Arjoto",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcReDstNPsz7R1DtlTfw9xHdX7HvLK8jumRoUrap6_RhENnfeA",
    "company": "Nusa teknogra indonesia",
    "role": "Private Investor",
    "quality": 4,
    "status": "Встреча состоялась",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/ari-yohan-arjoto-3b3396395",
    "comment": "",
    "campaign": "13.12 / Indonesia - Malaysia / private investors"
  },
  {
    "id": "w7-l20",
    "weekId": "Week 7",
    "name": "Pradipta Mullick",
    "photo": "https://media.licdn.com/dms/image/v2/C5603AQFEGDl9YaNF4A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1632818586180?e=1772064000&v=beta&t=t6msaKECm9jdym_LkC6gp6Ad8xdHfpuJKlnZ8tn5-mw",
    "company": "Intertran Technology",
    "role": "COO, Managing Director",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Chloé Boutiguila",
    "linkedin": "https://linkedin.com/in/pradiptamullick",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w7-l21",
    "weekId": "Week 7",
    "name": "Brenda Ng",
    "photo": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS_0nWCKEjtyrfT26j6cPYt1BgAp_lMLuYSkKR8-vonZGOn8w",
    "company": "The Facilitators' Project",
    "role": "Chief Fun(d) Officer (CFO)",
    "quality": 2,
    "status": "Встреча состоялась",
    "dateScheduled": "5.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/brenda-ng-3b391922",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w7-l22",
    "weekId": "Week 7",
    "name": "Shin Ito",
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTogcrMFc-w0oYCaXYQmxziTyx1UjEJrIMxopWRJ2rEX-TQHQ",
    "company": "",
    "role": "Founder, CEO & Representative Director at iKoyoo, Inc.",
    "quality": 5,
    "status": "Встреча состоялась",
    "dateScheduled": "4.02",
    "dateConducted": "February",
    "account": "Roman Vashkevich",
    "linkedin": "https://linkedin.com/in/shinito123",
    "comment": "",
    "campaign": "Japan - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w7-l23",
    "weekId": "Week 7",
    "name": "Angeline Siow",
    "photo": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTFqX8gBzk1adE8lOOA_UyzdECmIhythMgkiXzPL8lNRfV3fg",
    "company": "Grasshopper",
    "role": "Investor Relations Associate",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/angeline-siow-139a521b8",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  },
  {
    "id": "w7-l24",
    "weekId": "Week 7",
    "name": "Carly Bunni",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQHOlQvD7xLJUw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1724582255103?e=1772064000&v=beta&t=AKH7SIRqWwcfrvS7j0nfIJOFi0_YgwolnmcUX6ovYUY",
    "company": "Ardian",
    "role": "Investor Relations",
    "quality": 1,
    "status": "Встреча состоялась",
    "dateScheduled": "2.02",
    "dateConducted": "February",
    "account": "Igor Smirnov",
    "linkedin": "https://linkedin.com/in/carly-bunni-0845a9211",
    "comment": "",
    "campaign": "UAE - Angel investors - 3.10 (linkedIn search)"
  },
  {
    "id": "w7-l25",
    "weekId": "Week 7",
    "name": "Nicola Pellegrino",
    "photo": "https://media.licdn.com/dms/image/v2/D4D03AQGBqUm28opsdw/profile-displayphoto-crop_800_800/B4DZoLym1MHwAI-/0/1761134412784?e=1771459200&v=beta&t=iaokk4IXf7nK5TeROywt-vSydbo22FBFXYASua4VH4o",
    "company": "Eleven Plus Inc",
    "role": "investor & Advisor",
    "quality": 3,
    "status": "Встреча состоялась",
    "dateScheduled": "29.01",
    "dateConducted": "February",
    "account": "Alexandra Nazarova",
    "linkedin": "https://linkedin.com/in/npellegrino",
    "comment": "",
    "campaign": "Hong Kong - Angel/private investors - 9.10 (linkedIn search)"
  }
];
