leads_text = """
Week 2	1	Manuel Hadj-Rahmoun	ARES	Founder	4	January	05.01	January	Week 3	Igor Smirnov	https://linkedin.com/in/manuelhr	Встреча состоялась	Japan - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D5603AQGQw_86Y6uKcg/profile-displayphoto-crop_800_800/B56Zr2Uv5nHQAI-/0/1765069226432?e=1769644800&v=beta&t=4OWJURYUCQq5N1iZ9OyfDY7nW0kYhqvsU0PcpWWgP7Q
Week 2	2	Edwin John	Mumbai Angels	Venture Capital Advocate	2	January	05.01	January	Week 2	Igor Smirnov	https://linkedin.com/in/edwin-john-10a78051	Встреча состоялась	UAE - Angel investors - 2.10 (Dima's base)	https://media.licdn.com/dms/image/v2/D4D03AQFC8JNXNVHqvg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1723393264108?e=1769644800&v=beta&t=wkTbcjbe_MjiZhptapHHH_YDQ1fQJijDbVcRWJDoS3M
Week 2	3	Iuliia Skriaga	3S Money	Sales Operations Analyst	1	January	07.01	January	Week 3	Andrey Tsvetkov	https://linkedin.com/in/iuliia-skriaga-90257b215	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://media.licdn.com/dms/image/v2/D4D03AQFDm-UVhB_cnw/profile-displayphoto-crop_800_800/B4DZjTHz21H4AQ-/0/1755888698648?e=1769644800&v=beta&t=OeabtLwPyyX4_uEHahksNLJ6V_2G996l02Pm5GcfmHE
Week 2	4	Faisal Mahmood	Bahrain Economic Development Board	Investment Development Department	3	January	08.01	January	Week 3	Igor Smirnov	https://linkedin.com/in/faisal-mahmood-msf-2b0011b5	Встреча состоялась	13.12 / Qatar, Kuwait, Bahrain / private investors	https://media.licdn.com/dms/image/v2/D4D03AQHnn_xGe6IxOA/profile-displayphoto-crop_800_800/B4DZuPoLfXIYAM-/0/1767641234284?e=1769644800&v=beta&t=9AsLoc06aZsqUV4eZzHnbwWUr5hfrmkqZ7Uiof7Pyf4
Week 2	5	Scott Fletcher	FETCH	Investor and None Exec Chairman	3	January	09.01	January	Week 3	Andrey Tsvetkov	https://linkedin.com/in/scott-fletcher-mbe-223795158	Встреча состоялась	UAE - Angel investors - 3.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D4D03AQEbYCOsHQ6_sw/profile-displayphoto-crop_800_800/B4DZh7AxG8GsAU-/0/1754410456145?e=1769644800&v=beta&t=-FmzwdLaZC5PPoqZg6og5YxHUiRZBM4Bo0SwqSG_LhI
Week 3	6	Mazen Khatib	M7 Capital	Chief Investment Officer	4	January	12.01	January	Week 3	Igor Smirnov	https://linkedin.com/in/mazen-khatib-329b341	Встреча состоялась	13.12 / Qatar, Kuwait, Bahrain / private investors	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRZkZZE7nNj7nSZg06UikhCX0xORyTYV1RW99dbn9PI4-STFw
Week 3	7	Anastasiia Piven	KHK & Partners Limited	Investment Operations	4	January	12.01	January	Week 3	Igor Smirnov	https://linkedin.com/in/anastasiia-piven-24615921b	Встреча состоялась	UAE - Angel investors - 3.10 (linkedIn search)	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9QgZnHu_d3ifNxy9TXUDFq12aFO1i955Oirmt8DOP5UcVcg
Week 3	8	Eng Nayef Aljebreen	Uni-Ventures	Founder & CEO		January	12.01			Igor Smirnov	https://linkedin.com/in/nayefa	Запланирована 	Saudi - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSYs5KmP56n_HUeqlIzApGY1Rgvee-43CyQWlGM7BtPNO-lqg
Week 3	9	Nauman Abdal	Unifrutti Group	Head of Treasury & Investor Relations	4	January	12.01	January	Week 3	Igor Smirnov	https://linkedin.com/in/naumanabdal	Встреча состоялась	UAE - Angel investors - 3.10 (linkedIn search)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSAn-gXH7eIbCtrPqItWky1ECu7som14Kgf9MYhMcPGRHIc7Q
Week 3	10	Aman Kumar Soran	SBI Investment	Venture Capitalist	2	January	14.01	January	Week 4	Igor Smirnov	https://linkedin.com/in/aman-kumar-soran	Встреча состоялась	Japan - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSz6d7KlIuXNy-EtR01nEU2XTqBaRhunyd-fAF1SE6ci4x4hQ
Week 3	11	Ilya Etko	International Strategic Holding	Chief Strategy Officer	3	January	15.01	January	Week 4	Igor Smirnov	https://linkedin.com/in/ilyaetko	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRtRJtLtDlOFzUhwGxTeLhTxtWSkydAb3kZHBS_7lD5wQTcFA
Week 3	12	Leonard Belinga	venture capitalist	Private Investor		January	15.01			Roman Vashkevich	https://linkedin.com/in/leonard-belinga-17bb1720b	Запланирована 	13.12 /South Africa / private investors	no photo
Week 4	13	Freedom Magwaza	SPEED POWER ENTERPRISE	PRIVATE INVESTOR	2	January	19.01	January	Week 4	Elena Smirnova	https://linkedin.com/in/freedom-magwaza-66369b125	Встреча состоялась	13.12 /South Africa / private investors	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMMepxr1LZY8XjWNrh3zNAakyrGbGeegbPkvQA4NNdlnsv7A
Week 4	14	David Susanto	Zia Guild	Guild Master	1	January	19.02	January	Week 4	Roman Vashkevich	https://linkedin.com/in/davidsusanto	Встреча состоялась	13.12 / Indonesia - Malaysia / private investors	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyQIMCqtfEBin6CzhflvF0rcXTIwpJaqFM77-Jt1r5m9-uyw
Week 4	15	Anshul Agrawal	Imdaad Group	Energy Auditor	1	January	20.01	January	Week 4	Igor Smirnov	https://linkedin.com/in/anshul-agrawal-047a17b3	Встреча состоялась	Singapore - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D4D03AQGfIIcPeIRJMA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1692783087970?e=1770854400&v=beta&t=Ee0VCdmsoL986Nmftt473uW2ON80T0CXtnV1LeH9zBI
Week 4	16	Mohammad Jamal	Business Angels of Qatar	Angel Investor	2	January	20.01	January	Week 4	Valentina Pedro	https://linkedin.com/in/mohammad-malek-al-jamal-cfa-45058871	Встреча состоялась		https://media.licdn.com/dms/image/v2/D4D03AQHjTcPQI8LvnA/profile-displayphoto-shrink_800_800/B4DZrPZ47zJcAc-/0/1764416262375?e=1770854400&v=beta&t=B_remayj7v-_WvQUSk6waubH7RkdTdAlQr24W0Kgzyc
Week 4	17	Martin Glimmerholm	Self-Employed	Senior advisor – independent	5	January	20.01	January	Week 4	Igor Smirnov	https://linkedin.com/in/martin-glimmerholm-385a5925	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBEL5p6h3upkbMheqBGWasrM78b6lJiMfSEcXYG9Al3AbnjQ
Week 4	18	Tshepo Motlhetlhi	Alterra Capital Partners	Private Equity Investor	4	January	20.01	January	Week 4	Roman Vashkevich	https://linkedin.com/in/tshepo-motlhetlhi-55b68a53	Встреча состоялась	13.12 /South Africa / private investors	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpL1H8LPDavG5H8Hn0O8hOI8qYfSdQ0Yfn3JgVsWINJbAhfQ
Week 4	19	Ilya Kazakov	D360 Bank	Head of Risk Modeling & Analytics	1	January	21.01	January	Week 4	Igor Smirnov	https://linkedin.com/in/ilyaka	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://media.licdn.com/dms/image/v2/C4D03AQGGJ96uFUH0hQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1656319869289?e=1770854400&v=beta&t=p4xv9fcgxTlZ6xatDaLIKpaFRnLEVDF4wT4NOrHARRM
Week 4	20	Grace Yun Xia	xAI	Investor	3	January	22.01	January	Week 5	Igor Smirnov	https://linkedin.com/in/graceyunxia	Встреча состоялась	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ61RSxtUHHh-lCrdqYoAJ0IDvVR8yDXBfKWwV8KoJBKi_VA
Week 4	21	Chrissy H.	Reimagine X Studio	Investor & Founder & Creative Designer	4	January	22.01	January	Week 5	Roman Vashkevich	https://linkedin.com/in/chrissy-huang	Встреча состоялась	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	no photo
Week 4	22	Anwar Al-Yahya	Kuwait Finance House	Executive Manager	3	January	23.01	January	Week 5	Elena Smirnova	https://linkedin.com/in/anwar-hamad-al-yahya-80122826	Встреча состоялась	13.12 / Qatar, Kuwait, Bahrain / private investors	no photo
Week 5	23	Yulia Yakir	UBS	Director, Senior Credit Officer	2	January	27.01	January	Week 5	Igor Smirnov	https://linkedin.com/in/yulia-yakir-28239322	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://media.licdn.com/dms/image/v2/D4D03AQEF3P4z_8b-5Q/profile-displayphoto-crop_800_800/B4DZmC3KllHYAI-/0/1758837124280?e=1771459200&v=beta&t=sVNHTK9oDQE8XYKosiFUk_Vp2t9ACtxYN1ZAsJ51q1g
Week 5	24	Stanislav Krasov	SALIC	Investment (M&A) Director	1	January	27.01	January	Week 5	Igor Smirnov	https://linkedin.com/in/stanislavkrasov	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSw57laF1yEnrlmOIOZOQfYQYaC_bOShWHyIqScz8E4y_Agfg
Week 5	25	Talha A.	Self-Employed	Crypto investor and blockchain data analyst	2	January	27.01	February	Week 6	Igor Smirnov	https://linkedin.com/in/talha-a-aab136bb	Встреча состоялась	13.12 / Qatar, Kuwait, Bahrain / private investors	no photo
Week 5	26	Denis Kornyukhov	VTB	Quantitative Researcher	3	January	28.01	January	Week 5	Igor Smirnov	https://linkedin.com/in/hornyhov	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://media.licdn.com/dms/image/v2/D4D03AQEeEHWBZ39SsQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1723494903949?e=1771459200&v=beta&t=tQZg1SFe9gu_AM-4S-6_X2kGvbXFXOcGFvVWvTGMgUc
Week 5	27	Gédéon LALEMI	Trust Wallet	Cotonou, Benin		January	28.01			Igor Smirnov	https://linkedin.com/in/gedeonlalemi	Запланирована	UAE - Angel investors - 2.10 (Dima's base)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR4NpednWWLT42JI0L1dbUq3xncjEyRaEwlUc_f92d_WKCuAw
Week 5	28	Nicola Pellegrino	Eleven Plus Inc	investor & Advisor		January	29.01			Alexandra Nazarova	https://linkedin.com/in/npellegrino	Запланирована	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D4D03AQGBqUm28opsdw/profile-displayphoto-crop_800_800/B4DZoLym1MHwAI-/0/1761134412784?e=1771459200&v=beta&t=iaokk4IXf7nK5TeROywt-vSydbo22FBFXYASua4VH4o
Week 5	29	Maté Z.	Various Startups	Startup Advisor | Angel Investor	4	January	29.01	February	Week 6	Igor Smirnov	https://linkedin.com/in/matezgombic	Встреча состоялась	UAE - Angel investors - 2.10 (Dima's base)	https://media.licdn.com/dms/image/v2/D5603AQEfHZ0MT_5eQA/profile-displayphoto-crop_800_800/B56Znj7KNcI8AI-/0/1760465560739?e=1771459200&v=beta&t=DwD99a5o8cdZlFtRLdlbdEH5xBQ1zgPlImSmr86Z6W4
Week 5	30	Bradley Bester	Fiera Capital (Asia)	Director of Investor Relations	3	January	29.01	January	Week 5	Igor Smirnov	https://linkedin.com/in/bradley-bester-cfa	Встреча состоялась	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D5603AQG1DO2BeF0NiA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1731030341601?e=1771459200&v=beta&t=cnlMV05ucWFpx7omVdz4lQZUqvRGQCT7w0x8rqcw4no
Week 5	31	Ayla Mironova	AI-Bridge/Below Technologies	Chief Financial Officer, CBDO	3	January	30.01	February	Week 6	Alexandra Nazarova	https://linkedin.com/in/aylamironova	Встреча состоялась	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://media.licdn.com/dms/image/v2/D4E03AQGTtXzEjgs3AA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1700167090395?e=1771459200&v=beta&t=rWM6MtwSW9a4PDVOtAg7e4c7UAB-LH1ZBA7wdBkQdJc
Week 5	32	Eli Enoch	Silknet	Strategy and Investor Relations Officer		January	28.01			Roman Vashkevich	https://linkedin.com/in/elienoch	личная встреча	 22.01 / investors Georgia / face-to-face meeting	https://media.licdn.com/dms/image/v2/C4D03AQGTO466TcAceQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1659119060664?e=1771459200&v=beta&t=Tpi-5Bd02IriQKrNi-oV6C4C9n7XDOewgVjpXjg6Q5Q
Week 5	33	Levon Manucharyan	Green Rock Management Group	Chief Financial Officer		January	29.01			Roman Vashkevich	https://linkedin.com/in/levonmanucharyan	личная встреча	22.01 / investors CIS / face-to-face meeting	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUPQn6bTxZE8ky1KhWuiUxywh8CPxjMbnEjv0P1Ih88wtndw
Week 6	34	Angeline Siow	Grasshopper	Investor Relations Associate		February	2.02			Igor Smirnov	https://linkedin.com/in/angeline-siow-139a521b8	Запланирована	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTFqX8gBzk1adE8lOOA_UyzdECmIhythMgkiXzPL8lNRfV3fg
Week 6	35	Carly Bunni	Ardian	Investor Relations		February	2.02			Igor Smirnov	https://linkedin.com/in/carly-bunni-0845a9211	Запланирована	UAE - Angel investors - 3.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D4D03AQHOlQvD7xLJUw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1724582255103?e=1772064000&v=beta&t=AKH7SIRqWwcfrvS7j0nfIJOFi0_YgwolnmcUX6ovYUY
Week 6	36	Ts. T. (Zehan Teoh)	Finsall Resources	Angel Investor		February	2.02			Igor Smirnov	https://linkedin.com/in/zehant	Запланирована	13.12 / Indonesia - Malaysia / private investors	https://media.licdn.com/dms/image/v2/D5603AQEMviLy__6crA/profile-displayphoto-crop_800_800/B56ZvAyUIxIoAI-/0/1768465977926?e=1772064000&v=beta&t=RAeeqlVs0-FHAYCaCIcg17gGBScG0kf5VDuGvlbg1yQ
Week 6	37	Jon I. Bergsteinsson	Stealth Mode	Voice of MedTech | Industry Truth-Teller | MP @ LIFA.VC | Chair of IceBAN		February	2.02			Igor Smirnov	https://linkedin.com/in/joningib	отмена	UAE - Angel investors - 2.10 (Dima's base)	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcROueDnNKLdIxijzE9Y8BrIVbSBq1F5F83Ws9eSdwTB4DHNeA
Week 6	38	Matthew Baum	CBC Group	Associate - Investor Relations	2	February	2.02	February	Week 6	Roman Vashkevich	https://linkedin.com/in/matthew-baum-972354150	Встреча состоялась	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D5603AQEoeT3_LNAZXA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1691107914680?e=1772064000&v=beta&t=5-0_9lUwwX0D9KwGQtMuJt5GNydXRZvTQD385x6N79s
Week 6	39	Ali Janahi	National Bank of Bahrain	Head of Wealth Management		February	3.02			Chloé Boutiguila	https://linkedin.com/in/ali-janahi-557719188	Запланирована	13.12 / Qatar, Kuwait, Bahrain / private investors	https://media.licdn.com/dms/image/v2/D4E03AQEkMtPzj_-1Hw/profile-displayphoto-shrink_800_800/B4EZVGdc0tHUAc-/0/1740643881957?e=1772064000&v=beta&t=f1d0QxNdGgjQ_XwBRE1buRGG4waWbWU0hoV9BL-YeY0
Week 6	40	Ryаn Othmаn	MNO Partners	Founding Partner - Real Estate Development		February	3.02			Alexandra Nazarova	https://linkedin.com/in/ryan-othman	не отвечает 	Saudi - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/D5603AQGHQid2zbhqag/profile-displayphoto-crop_800_800/B56ZkAPPJvHkAU-/0/1756645619115?e=1772064000&v=beta&t=OZuMT4azujI1wdm9R_9G6vnq70F_cI69ErcOCjPKzME
Week 6	41	Talifa Isgandar	SABAH.HUB	Board Member		February	4.02			Ruslan Pshenin	https://linkedin.com/in/talifa-isgandar-459910192	личная встреча	22.01 / investors CIS / face-to-face meeting	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7aK6EnNxNedQWzX8_USInIQ4Qp2S2lYdwVB62BRPKa3TeLw
Week 6	42	David Tushishvili	Blockberg	Advisory Board Member		February	4.02			Ruslan Pshenin	https://linkedin.com/in/davidtushishvili	личная встреча	22.01 / investors Georgia / face-to-face meeting	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS9VwhVaP9ANe88CNF0wcoh69hGGpu4VJ83OuC4UhoM3SsNMw
Week 6	43	Tornike Revishvili	Skyward Solutions	Chief Operating Officer		February	4.02			Ruslan Pshenin	https://linkedin.com/in/tornike-revishvili-a28b7899	личная встреча	22.01 / financial advisors Georgia / face-to-face meeting--copy	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRWlaFeJhOKencYhjTt31rKx8SiaDpfjaXXFzRIMq2Iscm3NA
Week 6	44	Shin Ito		Founder, CEO & Representative Director at iKoyoo, Inc.		February	4.02			Roman Vashkevich	https://linkedin.com/in/shinito123	Запланирована	Japan - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTogcrMFc-w0oYCaXYQmxziTyx1UjEJrIMxopWRJ2rEX-TQHQ
Week 6	45	Mikha Tamasidze	Anko	Chief Financial Officer		February	4.02			Ruslan Pshenin	https://linkedin.com/in/mikha-tamasidze-924191182	личная встреча	22.01 / financial advisors Georgia / face-to-face meeting--copy	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRdpg2x_qhLT_rNR7JsKadLTGTUMuFW00-zzuJfgDKiJiA-uw
Week 6	46	Vahagn Mughnetsyan	Enterprise Armenia	Head of Investor Support and Aftercare Service Department		February	5.02			Ruslan Pshenin	https://linkedin.com/in/vahagnmughnetsyan	личная встреча	22.01 / investors CIS / face-to-face meeting	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQdwku6KO0LmgSOA6eHUaQliimgtQBS9geoWISvdIVRwwwEqg
Week 6	47	Nikoloz Alavidze	Impact Fund Actio	Actio Impact Fund Impact investor		February	5.02			Ruslan Pshenin	https://linkedin.com/in/nikoloz-alavidze-85629843	личная встреча	22.01 / investors Georgia / face-to-face meeting	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS1G-E5PFRN-tJqeBJm1od-Zthn7HdWuRGFFJjLR8dLwAMW9w
Week 6	48	Ari Arjoto	Nusa teknogra indonesia	Private Investor		February	5.02			Igor Smirnov	https://linkedin.com/in/ari-yohan-arjoto-3b3396395	Запланирована	13.12 / Indonesia - Malaysia / private investors	https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcReDstNPsz7R1DtlTfw9xHdX7HvLK8jumRoUrap6_RhENnfeA
Week 6	49	Pradipta Mullick	Intertran Technology	COO, Managing Director		February	5.02			Chloé Boutiguila	https://linkedin.com/in/pradiptamullick	Запланирована	Japan - Angel/private investors - 9.10 (linkedIn search)	https://media.licdn.com/dms/image/v2/C5603AQFEGDl9YaNF4A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1632818586180?e=1772064000&v=beta&t=t6msaKECm9jdym_LkC6gp6Ad8xdHfpuJKlnZ8tn5-mw
Week 6	50	Brenda Ng	The Facilitators' Project	Chief Fun(d) Officer (CFO)		February	5.02			Igor Smirnov	https://linkedin.com/in/brenda-ng-3b391922	Запланирована	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS_0nWCKEjtyrfT26j6cPYt1BgAp_lMLuYSkKR8-vonZGOn8w
Week 6	51	Giorgi Kasradze		CEO @ ELT Building | MBA, Corporate Finance		February	5.02			Ruslan Pshenin	https://linkedin.com/in/giorgi-kasradze-7627244	Запланирована	22.01 / financial advisors Georgia / face-to-face meeting--copy	https://media.licdn.com/dms/image/v2/D4D03AQGt--M7VWu9tg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1679464564799?e=1772064000&v=beta&t=4XMunX4dKBCsL9JV3pk0MeFGWnXl6B6_Y51h4HisPu4
Week 6	52	Zhibek Karamanova	Keremet Real Estate LLP	Founder		February	5.02			Ruslan Pshenin	https://linkedin.com/in/zhibek-karamanova-6768a05	личная встреча	22.01 / investors CIS / face-to-face meeting	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSebXF1Ew34dzcwESQRERI-yGTVm12G8qaXhV_6Bu9McvhsmA
Week 6	53	Georgy Grib	Tech Horizons Venture	Venture Studio Consultant		February	6.02			Ruslan Pshenin	https://linkedin.com/in/georgy-grib-187b884	Запланирована	22.01 / investors CIS / face-to-face meeting	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXEOpluWg98eaL7061pVkXPPcAbtKzOokuWUVBfS73xygxTA
Week 6	54	Karan Pawani	Silverdale Capital Pte Ltd	Investor Relations Associate		February	6.02			Roman Vashkevich	https://linkedin.com/in/karan-pawani	Запланирована	Hong Kong - Angel/private investors - 9.10 (linkedIn search)	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTTstw2PaWXdq0J9a0C2fw3qRqE6FqzuhaBL5Qt3Z4V5Uz1DQ
Week 6	55	Any Widjaja	Festive Fields Entertainment	Investor		February	6.02			Roman Vashkevich	https://linkedin.com/in/any-luvena-widjaja-33220a269	Запланирована	13.12 / Indonesia - Malaysia / private investors	https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSUvsah25ecpKMnXblo3M822AAoVTj_YrQidNG2OzHMi6POgQ
Week 6	56	Konstantin Shevchenko	"Waterfall View" LLC	Owner’s Representative (Land Sale & Development)		February	6.02			Roman Vashkevich	https://linkedin.com/in/konstantin-shevchenko-77351b31	личная встреча	22.01 / investors Georgia / face-to-face meeting	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu55J9UAJKvYGC7RtuiW_5HBCLxyEHLNMqOmymTScwxoe7ZQ
Week 6	57	Evgenia Zarubin	Core Realty Accosiates Inc	номер передан Саше		February	6.02			Igor Smirnov	https://linkedin.com/in/evgenia-zarubin	Запланирована	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTvd8G55m3eY9ocqKlQo557_NMN4p73ExknvDDte5N3V4bTzw
Week 6	58	Maria Erokhina	JSC Sberbank	Executive Director, Project manager		February	6.02			Roman Vashkevich	https://linkedin.com/in/maria-erokhina-850303345	Запланирована	21.10 - Ex-employees of Sberbank, VTB, Alfa-Bank, Gazprombank, Otkritie - formal vs. familiar tone and opinion query vs. direct call offer	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRXAKiT50wgYMuR34M6aFPXPzlOuvCwYJjuP4mUpDZoF7O-TQ
"""

import json

lines = leads_text.strip().split('\n')
parsed_leads = []

for line in lines:
    parts = line.split('\t')
    if len(parts) < 15:
        # Pad with empty strings if missing columns
        parts += [''] * (15 - len(parts))
    
    week_id = parts[0].strip()
    seq_num = parts[1].strip()
    name = parts[2].strip()
    company = parts[3].strip()
    role = parts[4].strip()
    quality_str = parts[5].strip()
    # parts[6] is word month
    date_scheduled_spec = parts[7].strip()
    # parts[8] is conducted month
    date_conducted_spec = parts[9].strip()
    account = parts[10].strip()
    linkedin = parts[11].strip()
    status = parts[12].strip()
    campaign = parts[13].strip()
    photo = parts[14].strip()
    
    quality = int(quality_str) if quality_str.isdigit() else None
    
    # Generate unique ID based on week and sequence number
    lead_id = f"{week_id.lower().replace(' ', '')}-l{seq_num}"
    
    lead = {
        "id": lead_id,
        "weekId": week_id,
        "name": name,
        "photo": photo if photo and photo != 'no photo' else f"https://ui-avatars.com/api/?name={name.replace(' ', '+')}&background=0D8ABC&color=fff",
        "company": company,
        "role": role,
        "quality": quality,
        "status": status,
        "dateScheduled": date_scheduled_spec,
        "dateConducted": date_conducted_spec,
        "account": account,
        "linkedin": linkedin,
        "comment": "",
        "campaign": campaign
    }
    parsed_leads.append(lead)

print(json.dumps(parsed_leads, indent=2, ensure_ascii=False))
